export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const GENERATE_LINK_TOKEN = 'GENERATE_LINK_TOKEN';
export const GENERATE_LINK_TRANSACTIONS = 'GENERATE_LINK_TRANSACTIONS';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const PARSE_TRANSACTIONS = 'PARSE_TRANSACTIONS';
export const PARSE_ACCOUNTS = 'PARSE_ACCOUNTS';
